(module
  (export "mem" (memory $main))
  (export "complexadd" (func $complexadd))
  (memory $main 1)
  (func $inc_ptr_64 (param i32) (result i32)
    (get_local 0)
    (i32.const 8)
    (i32.add)
    (return)
  )
  (func $complexadd (param i32) (param i32) (param i32) (result i32)
    (get_local 2)
    (get_local 0)
    (i64.load)
    (get_local 1)
    (i64.load)
    (i64.add)
    (i64.store)

    (get_local 2)
    (call $inc_ptr_64)
    (get_local 0)
    (call $inc_ptr_64)
    (i64.load)
    (get_local 1)
    (call $inc_ptr_64)
    (i64.load)
    (i64.add)
    (i64.store)
    (get_local 2)

    (return)
  )
)
