(module
  (export "mem" (memory $main))
  (export "sum" (func $sum))
  (memory $main 10)
  (func $sum (param i32) (param i32) (result i32)
    (local i32)
    (local i32)
    (i32.const 4)
    (get_local 1)
    (i32.mul)
    (get_local 0)
    (i32.add)
    (set_local 2)
    (block
      (loop
        (get_local 0)
        (get_local 2)
        (i32.eq)
        (br_if 1)
        (get_local 0)
        (i32.load)
        (get_local 3)
        (i32.add)
        (set_local 3)
        (i32.const 4)
        (get_local 0)
        (i32.add)
        (set_local 0)
        (br 0)
      )
    )
  (get_local 3)
  )
)
